///

//      CRUD

///

// GET CONTENT
GET http://www.localhost:8000 HTTP/1.1 

###

// GET CONTENT FROM DATABASE
GET http://www.localhost:8000/pokemon HTTP/1.1
content-type: application/json

###
// TRY TO CREATE A REGISTER IN DATABASE
POST http://www.localhost:8000/pokemon HTTP/1.1
content-type: application/json

{
    "name": "Flavio",
    "type": "Developer",
    "gen": 1
}
###
// TRY TO CREATE A NEW REGISTER INTO THE DATABASE WITHOUT SEND ANY DATA
// IT WILL RETURN ERROR
POST http://www.localhost:8000/pokemon HTTP/1.1
content-type: application/json
{
}
###
//  TRY UPDATE A REGISTER FROM THE DATABASE
PUT http://www.localhost:8000/pokemon/1 HTTP/1.1
content-type: application/json
{
    "name": "Gabriel",
    "gen": 10
}
###
//  TRY UPDATE A REGISTER PASSING A WRONG JSON
//  RETURNS AN ERROR
PUT http://www.localhost:8000/pokemon/1 HTTP/1.1
content-type: application/json

{
    "asd":"wrong format"
    asd,
    ,,asd
}

###
// TRY TO DELETE A REGISTER FROM THE DATABASE
GET  http://www.localhost:8000/pokemon/1 HTTP/1.1
content-type: application/json
{
}
###
// WRONG JSON FORMAT
PUT http://www.localhost:8000/pokemon/1 HTTP/1.1
content-type: application/json

{






              a:1
}