//success
GET http://35.199.94.103 HTTP/1.1 
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

//Success
GET http://35.199.94.103/pokemon HTTP/1.1
content-type: application/json

{
}

###
//error
POST http://35.199.94.103/pokemon HTTP/1.1
content-type: application/json

{
    
}

###
//error
POST http://35.199.94.103/pokemon HTTP/1.1
content-type: application/json

{
    "asd":"wrong format"
    asd,
    ,,asd

}

###
//successs
POST http://35.199.94.103/pokemon HTTP/1.1
content-type: application/json

{
    "name": "Flavio",
    "type": "Developer"
}

###
//success
GET http://35.199.94.103/pokemon/1 HTTP/1.1
content-type: application/json

{
}

###
//success
PUT http://35.199.94.103/pokemon/1 HTTP/1.1
content-type: application/json

{
    "name": "Gabriel"
}

###
//success
GET http://35.199.94.103/pokemon/1 HTTP/1.1
content-type: application/json

{
}

###

DELETE http://35.199.94.103/pokemon/1 HTTP/1.1
content-type: application/json

{
}
###

GET  http://35.199.94.103/pokemon/1 HTTP/1.1
content-type: application/json

{
}

###

//error
PUT http://35.199.94.103/pokemon/1 HTTP/1.1
content-type: application/json

{






              a:1
}