FROM mysql

ENV MYSQL_ALLOW_EMPTY_PASSWORD 1

ENV MYSQL_DATABASE "api"

ENV MYSQL_USER "flda-sil"

ENV MYSQL_PASSWORD "pa$$word123."

#docker run --name my_sql -e MYSQL_ROOT_PASSWORD=pa$$word123. -e MYSQL_DATABASE=api -e MYSQL_USER=flda-sil -e MYSQL_PASSWORD=pa$$word123.  -d mysql